apiVersion: apps/v1
kind: Deployment
metadata:
  name: library5-deployment 
  labels:
    project: library5
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      project: library
  template:
    metadata:
      labels:
        project: library
    spec:
      containers:
        - name: library5-container
          image: sriramsrb/library5:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "50m"

---

apiVersion: v1
kind: Service
metadata:
  name: library5-service 
  labels:
    project: library
spec:
  type: NodePort
  selector:
    project: library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
